# Generated by Django 4.2.10 on 2024-12-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_fleet_log_log_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet_log',
            name='log_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
