# Generated by Django 4.2.10 on 2024-12-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_fleet_log_log_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet_log',
            name='km_driven',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
