# Generated by Django 4.2.10 on 2024-12-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_fleet_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleet',
            name='supervisor',
        ),
        migrations.AlterField(
            model_name='fleet',
            name='driver',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
