# Generated by Django 4.2.10 on 2024-12-07 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_country_fieldoffice_region_zone_woreda_profile_and_more'),
        ('fleet', '0008_remove_fleet_supervisor_alter_fleet_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('make', models.CharField(blank=True, max_length=255, null=True)),
                ('hour_liter', models.FloatField(blank=True, null=True)),
                ('person_in_charge', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('field_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.fieldoffice')),
            ],
        ),
    ]
