# Generated by Django 4.2.10 on 2024-12-07 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_generator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generator_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_report', models.CharField(blank=True, max_length=255, null=True)),
                ('year_report', models.IntegerField(blank=True, null=True)),
                ('operated_time_hr', models.FloatField(blank=True, null=True)),
                ('fuel_used_lt', models.FloatField(blank=True, null=True)),
                ('fuel_cost_br', models.FloatField(blank=True, null=True)),
                ('repair_cost_br', models.FloatField(blank=True, null=True)),
                ('generator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fleet.generator')),
            ],
        ),
    ]
