# Generated by Django 4.2.10 on 2024-12-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0010_generator_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='generator',
            name='generator_pic',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
