# Generated by Django 4.2.10 on 2024-12-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0011_generator_generator_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='generator_report',
            name='report_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
