# Generated by Django 4.2.10 on 2024-12-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0017_alter_missed_expense_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log_Report',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tag_number', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=255, null=True)),
                ('ownership', models.CharField(blank=True, max_length=255, null=True)),
                ('month_log', models.CharField(blank=True, max_length=255, null=True)),
                ('year_log', models.IntegerField(blank=True, null=True)),
                ('km_driven', models.FloatField(blank=True, null=True)),
                ('day_use', models.IntegerField(blank=True, null=True)),
                ('day_available', models.IntegerField(blank=True, null=True)),
                ('day_total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'log_report',
                'managed': False,
            },
        ),
    ]
