# Generated by Django 4.2.10 on 2024-12-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0018_log_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense_Report',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tag_number', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=255, null=True)),
                ('ownership', models.CharField(blank=True, max_length=255, null=True)),
                ('expense_start_date', models.DateField(blank=True, null=True)),
                ('month_expense', models.CharField(blank=True, max_length=255, null=True)),
                ('year_expense', models.IntegerField(blank=True, null=True)),
                ('total_cost', models.FloatField(blank=True, null=True)),
                ('spare_cost', models.FloatField(blank=True, null=True)),
                ('fuel_cost', models.FloatField(blank=True, null=True)),
                ('consumable_cost', models.FloatField(blank=True, null=True)),
                ('rental_and_tax_cost', models.FloatField(blank=True, null=True)),
                ('labour_cost', models.FloatField(blank=True, null=True)),
                ('rental_cost', models.FloatField(blank=True, null=True)),
                ('tax_cost', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'expense_report',
                'managed': False,
            },
        ),
    ]
