# Generated by Django 4.2.10 on 2024-12-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0019_expense_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='generator_report',
            name='gen_log_sheet',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
